### ISSUE TITLE
devops-iac-eks-policy.json role question

### ISSUE THREAD

**Issue by sasbg** [sassoftware/viya4-iac-aws#199]
Regarding devops-iac-eks-policy.json, our customer is asking what are the following two roles used for and can they be omitted:
iam:CreateOpenIDConnectProvider 
iam:CreateDBInstance

**Comment by ricciardi7** [comment]
The customer commented that they need some information / documentation regarding the purpose of the required roles so that they can submit for approval to use them temporarily assuming they cannot be omitted.  Appreciate any insights that can be provided.  Thanks.

**Comment by dhoucgitter** [comment]
Repeating the answer provided elsewhere for background information.

For the two policies listed, iam:CreateOpenIDConnectProvider is the only one I found in the referenced json file.

The IaC AWS terraform source uses two modules, aws_autoscaling and aws_ebs_csi. Both of them reference the iam_assumable_role_with_oidc terraform module to create roles which are needed to grant permissions via service accounts in the K8S cluster.
The iam_assumable_role_with_oidc module requires the oidc provider as an input argument in order to be able to create the assumable roles.

The OIDConnectProvider resource is created by the EKS module which can be seen when IaC for AWS runs the plan or apply phases

 # module.eks.aws_iam_openid_connect_provider.oidc_provider[0] will be created
  + resource "aws_iam_openid_connect_provider" "oidc_provider" {

For iam:CreateOpenIDConnectProvider, I'd expect that omitting that policy would cause the step above to fail without the necessary permissions and would result in a plan or apply failure.
