### ISSUE TITLE
 Feature: naming of AutoscaleGroups in AWS

### ISSUE THREAD

**Issue by biohazd** [sassoftware/viya4-iac-aws#249]
Please can you name the AutoscaleGroups created in AWS the same as all other resoruces, namely with the {{ NAMESPACE }}

currently it uses random numbers and letters:
eks-stateful-2023080910034681350000002f-d8csdfsdfe0-5f26-b639-0376-e6besdfdfsa9f8b40

new naming scheme
{{ NAMESPACE }}-eks-stateful-2023080910034681350000002f-d8csdfsdfe0-5f26-b639-0376-e6besdfdfsa9f8b40

**Comment by jarpat** [comment]
Hey @biohazd,

The creation of the AutoscaleGroups in AWS happens during infrastructure creation time and not during the deployment part in the viya4-deployment project. So I'll be moving this issue over to the [viya4-iac-aws](https://github.com/sassoftware/viya4-iac-aws) repo since it's more relevant there.

As far as naming goes, the name is generated based off the `name` parameter used for each node pool when setting the [`eks_managed_node_groups` parameter](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/submodules/eks-managed-node-group). In `viya4-iac-aws` this value is sourced from each key in our `node_pools` map here: https://github.com/sassoftware/viya4-iac-aws/blob/main/examples/sample-input.tfvars#L41

So if you wanted a custom name you could update `stateful` key to any valid value you would like.
