### ISSUE TITLE
Mismatch between doc and subnets generated

### ISSUE THREAD

**Issue by miaeyg** [sassoftware/viya4-iac-aws#256]
According to the doc at https://github.com/sassoftware/viya4-iac-aws/blob/main/docs/CONFIG-VARS.md#subnet-requirements

It says:

_If no values are set for the [subnet_ids](https://github.com/sassoftware/viya4-iac-aws/blob/main/docs/CONFIG-VARS.md#use-existing) configuration variable, viya4-iac-aws will create subnet resources for you. By default, a private subnet, two control_plane subnets, two public subnets and two database subnets will be created_

However, when I ran the script with no subnet_id provided (scenario 0 = everything built by the terraform script) I saw something else:

2 private subnets (which the doc says this is not recommended by SAS)
2 public subnets
2 database subnets (although I did not ask to create an external PostgreSQL)
0 control plane subnets

What am I missing?

**Comment by dhoucgitter** [comment]
Hi @miaeyg, what version of viya4-iac-aws are you using? The CONFIG-VARS.md URL for the main branch that you reference documents the current behavior for [Release 8.0.0](https://github.com/sassoftware/viya4-iac-aws/releases/tag/8.0.0) or later. If you are using a version prior to 8.0.0 that would explain the behavior you are seeing.

**Comment by miaeyg** [comment]
Hi David,

You were correct. I was reading the new doc while using an older version. Sorry for the mess.

Eyal

**Comment by miaeyg** [comment]
By the way, how can I know which exact version of this project I have cloned? I assume there is some way to obtain this info from my local repo, not sure how to do it...

**Comment by dhoucgitter** [comment]
@miaeyg, after you clone the project, switch to the main branch and run `git log --decorate -1`.
You should seem something similar to this:
> commit faf3f0ebcc46cb4287fac70caac6733033d2e8b5 (HEAD -> main, **tag: 8.0.1**, origin/main, origin/HEAD, staging)
Merge: cee4a94 b682480
Author: XXX xxxx <78554593+xxxxx@users.noreply.github.com>
Date:   Tue Dec 12 13:33:23 2023 -0500
\
    Merge pull request #254 from sassoftware/staging
\
    8.0.1 - December 12, 2023

Look for the **tag:** value on the first line to confirm the release that you are on. The lat line of the commit comment also confirms this was the commit marking the 8.0.1 release.

**Comment by miaeyg** [comment]
Hi @dhoucgitter, with the latest version of this project I see two "db-subnets" created and I do not understand that is their usage. I did _not_ select to create an external PostgreSQL. Here is the relevant section from my terraform.tfvars file:

# postgres_servers = {
#   default = {},
# }

Can you please explain why two "db-subnets" are created in this case? What is their purpose?

**Comment by dhoucgitter** [comment]
Hi @miaeyg, could you attach your complete terraform-input.tfvars file and share the command that you are using to run viya4-iac-aws so I can try to reproduce that behavior, thanks.

**Comment by miaeyg** [comment]
Hi @dhoucgitter , attached is the input tfvars file (renamed to "txt" suffix just for upload here). Note that I masked values for "default_public_access_cidrs" but you need to trust me there were real IP addresses there.

This is the command used to invoke Terraform:

`sudo docker run --rm --group-add root --user "$(id -u):$(id -g)" --env-file=/home/sasinst/AWS/mia-iac-aws/.aws_nimbus_docker_creds.env --volume=$HOME/.ssh:/.ssh --volume=$(pwd):/workspace --volume=/home/sasinst/AWS/mia-iac-aws:/miaws viya4-iac-aws plan -var-file=/miaws/terraform-public-nimbus.tfvars -state=/workspace/terraform.tfstate
`
[terraform-public-nimbus.txt](https://github.com/sassoftware/viya4-iac-aws/files/13910703/terraform-public-nimbus.txt)

**Comment by dhoucgitter** [comment]
@miaeyg, with your current configuration, viya-iac-aws manages all the subnets for you, the [behavior ](https://github.com/sassoftware/viya4-iac-aws/blob/main/docs/CONFIG-VARS.md#subnet-requirements) for subnet creation when you don't pre-create your own set of subnets is:
> If no values are set for the `subnet_ids` configuration variable, `viya4-iac-aws` will create subnet resources for you. By default, a `private` subnet, two `control_plane` subnets, two `public` subnets and two `database` subnets will be created.

You have commented out the postgres_servers map in your configuration which will prevent the rds module from creating an external postgres db, however, that will not prevent viya4-iac-aws from creating the subnets defined in the default subnets map which includes 2 database subnets. As the documentation states, the current behavior for viya4-iac-aws where no `subnet_ids` map is defined is to create all the subnets in the `subnets` map. In case you think of trying it, removing the `database` key from the `subnets` map to try to prevent viya4-iac-aws from creating a flavor of subnets will result in a TF plan/apply error as values for all four subnet keys are expected with today's behavior. As long as there are no resources using the provisioned database subnets in you configuration, you could experiment with trying to manually delete them from the console and then test that your subsequent deployment is working as intended.
It does add additional complexity, but if you would like full control over which subnets are present for your deployment, you can create them ahead of time and then specify their subnet ids using the [`subnet_ids`](https://github.com/sassoftware/viya4-iac-aws/blob/main/docs/CONFIG-VARS.md#use-existing) map variable. Refer to the Subnet requirements documentation for which subnets you will need for a given configuration. In your case, you could omit the database subnets in your `subnet_ids` map. I'd recommend reading [Supported Scenarios and Requirements for Using Existing Network Resources](https://github.com/sassoftware/viya4-iac-aws/blob/main/docs/user/BYOnetwork.md#supported-scenarios-and-requirements-for-using-existing-network-resources) if you decide to take the existing subnets approach since there are additional requirements that you need to manage on your own.
