### ISSUE TITLE
pod limit per node

### ISSUE THREAD

**Issue by ricgatti** [sassoftware/viya4-iac-aws#257]
Hello, we have used the terraform file to create all the infrastructure, but we notice that with the vm used for node we have tha maximun pod per nodes to 58.

We used the r5.2xlarge for stateles and stateful nodepool. The number 58 is correct as also reported in AWS documentation.

Is there a way to add the option max-pods-per-node and set to 110 to avoid this limitation?

We also set the env variable ENABLE_PREFIX_DELEGATION=true in the aws-node daemonset and restarted the node but the number doesn't increase

**Comment by dhoucgitter** [comment]
Hi @ricgatti, could you share the contents of your terraform-input.tfvars so that I can replicate your scenario? Also, if you could expand on where you are seeing the 58 pod value limit 
>  but we notice that with the vm used for node we have tha maximun pod per nodes to 58.

and describe at what point in the deployment process are you noticing that limit.

An AWS discussion on [ENI allocation ](https://github.com/aws/amazon-vpc-cni-k8s#eni-allocation) describes how IP space grows as the number of pods running on a node increases. Is the 58 pod per node limit a value that you see prior to deploying Viya or have you reached that limit after trying to deploy Viya already?

AWS doc indicates that an r5.2xlarge instance can support up to 4 ENI interfaces which would provide support for 110 pods.

Could you share the AWS doc reference where you see this fact?
>We used the r5.2xlarge for stateles and stateful nodepool. The number 58 is correct as also reported in AWS documentation.

**Comment by dhoucgitter** [comment]
@ricgatti, looking at some additional information it appears that the maximum number of IPv4 addresses per interface is variable and changes based on the maximum ENIs. It looks like you may be hitting a limitation of the r5.2xlarge VM type that you've selected.

According to the amazon-eks-ami formula listed [here](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt#L33-L39) 

>  \# of ENI * (# of IPv4 per ENI - 1) + 2

and the values in the _IP addresses per network interface per instance type_ table [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#enis-memoryoptimized)

|Instance type	|Maximum network interfaces	|Private IPv4 addresses per interface	|IPv6 addresses per interface|
|-|-|-|-|
|m5.2xlarge	|4	|15	|15|
|m5.4xlarge	|8	|30	|30|

plugging in the values for m5.2xlarge results in 
  4 * (15 - 1) + 2  = 58 pods maximum

It looks like moving up to an r5.4xlarge instance type would give you the IP space that you need

  = 8 * (30-1) + 2 = 234 pods maximum
  
Given their formula, any of the r*.xlarge and r*2xlarge instance types in the memory optimized table would appear to only support a max of 58 pods per node.

**Comment by ricgatti** [comment]
thanks for the clarification, so there is no way creating a nodegroup manually with a m5.2xlarge with the max pod per node to 110? Maybe using the eksctl CLI

**Comment by miaeyg** [comment]
Check this link: https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html got this link from SAS EEC

**Comment by ricgatti** [comment]
Hello, Thanks for the link. I'v already tried but without success, seems the only way is to manually create the nodegroup with the max-pods option.
We have decided to add a new node to avoid this problem.

I think we can close the issue.
