### ISSUE TITLE
Add single AZ deployment option (or default?)

### ISSUE THREAD

**Issue by shealym** [sassoftware/viya4-iac-aws#91]
Greetings,

For public cloud deployments, the SAS performance team (Margaret Crevar, Tony Brown, etc) has always recommended deploying SAS servers as close together as possible...definitely in the same datacenter (AZ), preferably in a Placement Group...to minimize network and shared-storage latency.

It looks like EKS mandates having at least two subnets in different datacenters, but tinkering around, it appears that Autoscaling Groups can be set for one AZ.  Would it be possible to either option or force that configuration in viya4-iac-aws, to put Viya4 in the most performant configuration possible out of the gate?

Michael

**Comment by henriquedanc** [comment]
Hi,
Just want to add that this might be required if using gp2 disks for RWO.
I did some tests, and one of the times I couldn't get the environment to restart, because one crunchy disk was created in AZ B, but after scaling the node group up, the node was created AZ A, and you can't mount disks cross-AZs.

**Comment by johncurran** [comment]
Requested too. Hit same issue as henriquedanc with gp2 disks

**Comment by jarpat** [comment]
Closing, #239 implements `EKS Node Pool Subnets to use Single AZ by Default`
